#!/bin/sh

{ command -v curl && command -v git; } >/dev/null ||
    { echo Install curl and git >&2; exit 1; }

for d in $HOME/*; do
    rmdir "$d" 2>/dev/null
done
dotfiles="$HOME/etc/conf/dot"
bin="$HOME/etc/conf/bin"
backup="$HOME/.cache/backup"
conf="$HOME/etc/conf"

dirs="tmp work opt var/appdata .cache/backup .local/bin var/Rlib" 

xdg="$HOME/xdg"
user_dirs="$HOME/.config/user-dirs.dirs"
desktop=top
download=load
publicshare=share

### Working directories

cd "$HOME" && for d in $dirs; do
    mkdir -p "$d"
done

### Dotfiles

cd $HOME 
for f in $dotfiles/*; do
    tmp=.`basename "$f"`
    if ! [ -L "$tmp" ]; then
        mv -v "$tmp" "$backup/dot.$tmp"
    fi
    ln -sfv "$f" "$tmp" 
done

### Bin

cd $HOME && mkdir -p bin
cd $HOME/bin

for f in $bin/*; do
    ln -v -sf "$f"
done

### Standard dirs

tmp=`mktemp`

# my user-dirs file
if [ -e "$user_dirs" ]; then
    sed -r '/^#/!{
    s/=.*$//; h
    s/^.*_(.*)_.*$/\L\1/
    s/desktop/'"$desktop"'/
    s/download/'"$download"'/
    s/publicshare/'"$publicshare"'/
    H;x;
    s!\n!="'"$xdg/"'!
    s!$!/"!
    }
    ' "$user_dirs" >"$tmp"

    # create dirs
    sed -r -n '/^#/!{
    s!.*/([^/]*)/"$!\1!p
    }' "$tmp" |
    while read d; do
        mkdir -vp "$xdg/$d/"
    done

    mv -v "$tmp" "$user_dirs"
fi

### ssh
cd $HOME && ln -vfs -T $HOME/etc/priv/ssh .ssh

#### Tweaks

mkdir -p $HOME/.config

# Nvim
cd $HOME/.config
ln -sfv $conf/misc/vim/nvim 

# mc
# nope - there are others files
# ln -s $conf/misc/mc/ $HOME/.config
mkdir -p $HOME/.config/mc
ln -s $conf/misc/mc.keymap $HOME/.config/mc/

# Code
mkdir -p $HOME/.config/Code/User
ln -s  $conf/misc/vscode/settings.json  $HOME/.config/Code/User/
ln -s  $conf/misc/vscode/keybindings.json  $HOME/.config/Code/User/

# SSH (they are from git with strange permissions)
cd $HOME
chmod 700 .ssh
cd .ssh
chmod 600 *

# ruby (sync with .profile)
mkdir -p $HOME/var/gems
cd       $HOME/var/gems
ln -s $HOME/.local/bin

# fd in debians
cd $HOME/bin && ln -s /usr/bin/fdfind fd

####  Plugins
curl --silent -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Install with Prefix+I. Update with Prefix+U
git clone --quiet https://github.com/tmux-plugins/tpm \
    ~/.tmux/plugins/tpm 2>/dev/null

