#!/bin/sh

echo Installing fzf...

cd /tmp
git clone https://github.com/junegunn/fzf
cd fzf
./install --bin 
mkdir -p $HOME/bin
mv bin/* $HOME/bin
mdir=$HOME/.local/share/man/man1
mkdir -p $mdir
mv man/man1/* $mdir
fdir=$HOME/.local/share/fzf
mkdir -p $fdir
mv shell/* $fdir
cd ..
rm -rf fzf
