#!/bin/sh

# ???
# sudo -S pacman -Syy

sudo -S pacman -Syu

sudo -S pacman -S  \
    jq          \
    fzf         \
    fd          \
    ripgrep     \
    trash-cli   \
    unrar       \
    p7zip       \
    aria2       \
    mc          \
    vifm        \
    tree        \
    git         \
    tmux        \
    zsh         \
    zsh-doc     \
    gvim        \
    htop        \
    lynx        \
    curl        \
    wget        \
    atool       \
    xclip       \
    xsel        \
    wmctrl      \
    cmake       \
    speedtest-cli   \
    translate-shell \
    fzf             \
    python-pip      \
    bat             \
    neovim          \
    lsb-release     \
    ttf-ubuntu-mono-nerd    \
    yt-dlp          \
    hyperfine       \
    ruby            \
    ruby-pry        \
    ruby-docs       \
    tk              \
    julia           \
    gnuplot         \
    zip             \
    unzip           \
    tig             \
    lazygit         \
    base-devel      \
# yay firefox-esr-bin xkb-switch
# or pamac build
#    vim-gtk3 + vim  => gvim
#    rar         \
#    shellcheck  - try to install a lot of haskell deps 

