#!/bin/sh

{ command -v curl && command -v git; } >/dev/null ||
{ echo Install curl and git >&2; exit 1; }

# get ETC, VAR, LIB
. $(dirname "$0")/../profile

# make dirs
vardirs="profile.d opt xdg" 

cd "$HOME" || exit
ln -fs "$ETC"/profile .profile

# $LIB/tmp - tmp stuff for backup
mkdir -p "$VAR" "$LIB" "$LIB/tmp" tmp

cd "$VAR" || exit
for d in $vardirs; do
    mkdir -p "$d"
done

# bin
mkdir -p "$HOME"/.local/bin "$HOME"/bin
cd "$HOME"/bin || exit
for f in $ETC/bin/*; do
    ln -sf "$f"
done

# not my xdg
mkdir -p "$HOME"/.config

cat <<END >"$HOME"/.config/user-dirs.dirs
XDG_DESKTOP_DIR="$XDG/top/"
XDG_DOWNLOAD_DIR="$XDG/load/"
XDG_TEMPLATES_DIR="$XDG/templates/"
XDG_PUBLICSHARE_DIR="$XDG/share/"
XDG_DOCUMENTS_DIR="$XDG/documents/"
XDG_MUSIC_DIR="$XDG/music/"
XDG_PICTURES_DIR="$XDG/pictures/"
XDG_VIDEOS_DIR="$XDG/videos/"
END

mkdir -p "$XDG"
cd "$XDG"  || exit
mkdir -p top load documents templates share music pictures videos
cd "$HOME" || exit

# init
for app in $ETC/apps/*; do
    [ -f "$app/init" ] && sh "$app/init"
done

# private config TODO
cd "$HOME" || exit
mkdir -p .ssh
chmod 700 .ssh
cd .ssh || exit
chmod 600 *

true
