#!/bin/sh

# get ETC, VAR, LIB
. $(dirname $0)/../profile

# make dirs
vardirs="profile.d tmp opt xdg" 

cd $HOME
ln -fs $ETC/profile .profile

mkdir -p $VAR $LIB

cd $VAR
for d in $vardirs; do
    mkdir -p $d
done

# bin
mkdir -p $HOME/.local/bin $HOME/bin
cd $HOME/bin
for f in $ETC/bin/*; do
    ln -sf "$f"
done

# xdg
$ETC/util/fix-xdg

# init
for app in $ETC/apps/*; do
    [ -f "$app/init" ] && sh "$app/init"
done
