#!/bin/sh

{ command -v curl && command -v git; } >/dev/null ||
{ echo Install curl and git >&2; exit 1; }

# get ETC, VAR, LIB
. $(dirname "$0")/../profile

# make dirs
vardirs="profile.d opt xdg" 

cd "$HOME" || exit
ln -fs "$ETC"/profile .profile

mkdir -p "$VAR" "$LIB" tmp

cd "$VAR" || exit
for d in $vardirs; do
    mkdir -p "$d"
done

# bin
mkdir -p "$HOME"/.local/bin "$HOME"/bin
cd "$HOME"/bin || exit
for f in $ETC/bin/*; do
    ln -sf "$f"
done

# xdg
mkdir -p "$HOME"/.config

cat <<END >"$HOME"/.config/user-dirs.dirs
XDG_DESKTOP_DIR="$LIB/xdg/top/"
XDG_DOWNLOAD_DIR="$LIB/xdg/load/"
XDG_TEMPLATES_DIR="$LIB/xdg/templates/"
XDG_PUBLICSHARE_DIR="$LIB/xdg/share/"
XDG_DOCUMENTS_DIR="$LIB/xdg/documents/"
XDG_MUSIC_DIR="$LIB/xdg/music/"
XDG_PICTURES_DIR="$LIB/xdg/pictures/"
XDG_VIDEOS_DIR="$LIB/xdg/videos/"
END

mkdir -p "$VAR"/xdg
cd "$VAR"/xdg || exit
mkdir -p top load documents music pictures videos
cd "$HOME" || exit

# init
for app in $ETC/apps/*; do
    [ -f "$app/init" ] && sh "$app/init"
done

# private config TODO
cd "$HOME" || exit
mkdir -p .ssh
chmod 700 .ssh
cd .ssh || exit
chmod 600 *

true
