#!/bin/sh

usage="Usage: $(basename $0) REPONAME"

nvrepo="$HOME/var/nvrepo"

conf=~/.config/nvim
share=~/.local/share/nvim
state=~/.local/state/nvim
cache=~/.cache/nvim

die() {
    echo "$1" >&1 && exit 1
}

! [ -e "$nvrepo" ] && die "Error: $nvrepo does not exist"

[ $# -ne 1 ] && die "$usage"

repo="$nvrepo/$1"

! [ -e "$repo" ] && die "Repository $repo does not exist"

t=
for f in "$conf" "$share" "$state" "$cache"; do
    if [ -e "$f" ]; then
        ! [ -L "$f" ] && t=1 && ls -d "$f"
    fi
done

[ "$t" ] && die "Some directories are not links"

for f in "$conf" "$share" "$state" "$cache"; do
    src=$(echo "$f" | sed -E 's!.*\W(\w*)/nvim$!\1!')
    src="$repo/$src/nvim"
    tgt=$(echo "$f" | sed -E 's!nvim!!')
    rm -v "$f"
    ln -vs "$src" "$tgt"
done
